### ISSUE TITLE
Revise información de registro

### ISSUE THREAD

**Issue by methodmann** [julianyus/subtitulamostv#1]
Ayer instalé el addon al encontrarlo en el foro de subtitulamos.tv pero cuando voy a buscar cualquier subtitulo me aparece el error y pone que revise la información de registro. Uso kodi 18.5. Está funcionando el addon? Gracias!

**Comment by edied2002** [comment]
Lo mismo digo, gracias

**Comment by susobaco** [comment]
Hola, a mi me da este error: (kodi 18.6 trisquel etiona ubuntu bionic based)

2020-03-08 20:00:40.806 T:140252294113024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'season'
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/script.xbmc.subtitulamostv/default.py", line 97, in <module>
                                                Search(item)
                                              File "/home/kodi/.kodi/addons/script.xbmc.subtitulamostv/default.py", line 55, in Search
                                                subtitles = buscador.GetMatchingSubtitles(fileInfo['title'],str(fileInfo["season"]), '{:02d}'.format(fileInfo['episode']))
                                            KeyError: 'season'
                                            -->End of Python script error report<--
2020-03-08 20:00:40.962 T:140252686407424   ERROR: GetDirectory - Error getting plugin://script.xbmc.subtitulamostv/?action=search&languages=Spanish&preferredlanguage=Spanish
2020-03-08 20:00:41.204 T:140252349200128 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-03-08 20:00:44.423 T:140252853249792 WARNING: Previous line repeats 6 times.
2020-03-08 20:00:44.423 T:140252853249792  NOTICE: [plugin.video.elementum] [36mDEBU  main         ▶ Notification     [0mGot notification from xbmc/Input.OnInputRequested: {"title":"Introduzca la cadena de búsqueda","type":"keyboard","value":"maniac s01e06"}
2020-03-08 20:00:44.857 T:140252349200128 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-03-08 20:00:47.171 T:140252853249792 WARNING: Previous line repeats 4 times.
2020-03-08 20:00:47.171 T:140252853249792  NOTICE: [plugin.video.elementum] [36mDEBU  main         ▶ Notification     [0mGot notification from xbmc/Input.OnInputFinished: null
2020-03-08 20:00:47.263 T:140252870035200  NOTICE: Indigo NOTICE: Checking for Malicious scripts
2020-03-08 20:00:47.493 T:140252349200128 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-03-08 20:00:47.534 T:140252302505728   ERROR: ### [subtitulamostv] - Buscar
2020-03-08 20:00:47.540 T:140252302505728   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'season'
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/script.xbmc.subtitulamostv/default.py", line 97, in <module>
                                                Search(item)
                                              File "/home/kodi/.kodi/addons/script.xbmc.subtitulamostv/default.py", line 57, in Search
                                                subtitles = buscador.GetMatchingSubtitles(item['mansearchstr'],str(fileInfo["season"]), '{:02d}'.format(fileInfo['episode']))
                                            KeyError: 'season'
                                            -->End of Python script error report<--

**Comment by julianyus** [comment]
Buenas, si mañana tengo algo de tiempo lo reviso. Probaré a instalarlo en un kodi limpio. Un saludo

**Comment by methodmann** [comment]
Se agradece,muchas gracias
